name: "Hello World Pipeline"
on: push
jobs:
  my-jobs:
    runs-on: ubuntu-latest
    steps:
     - name: my-step
       run: echo "Hello World!"
     - name: name-step
       run: echo "Diksha"
       name: rollno-step
       run: echo "24cb010"
       
